In [1]:
import pandas as  pd
import numpy as np
import os

In [2]:
s = pd.Series([10,20,30,40])

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
data = {
    "Name":["Lokesh","Ravi","Anu","Ritu"],
    "Age":[22,23,24,25]
}

df = pd.DataFrame(data)
print(df)

     Name  Age
0  Lokesh   22
1    Ravi   23
2     Anu   24
3    Ritu   25

In [4]:
df.head()      #First Five Rows

     Name  Age
0  Lokesh   22
1    Ravi   23
2     Anu   24
3    Ritu   25

In [5]:
df.tail()      #Last five rows

     Name  Age
0  Lokesh   22
1    Ravi   23
2     Anu   24
3    Ritu   25

In [6]:
 df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [7]:
df.describe()

             Age
count   4.000000
mean   23.500000
std     1.290994
min    22.000000
25%    22.750000
50%    23.500000
75%    24.250000
max    25.000000

In [8]:
df['Name']

0    Lokesh
1      Ravi
2       Anu
3      Ritu
Name: Name, dtype: object

In [9]:
df[['Name','Age']]

     Name  Age
0  Lokesh   22
1    Ravi   23
2     Anu   24
3    Ritu   25

In [11]:
df['salary']=[200,250,300,350]

In [16]:
print(df)

  Full_Name  Age  salary
0    Lokesh   22     200
1      Ravi   23     250
2       Anu   24     300
3      Ritu   25     350

In [13]:
df['Age'].value_counts()

Age
22    1
23    1
24    1
25    1
Name: count, dtype: int64

In [14]:
df['Age'].unique()

array([22, 23, 24, 25], dtype=int64)

In [15]:
df.rename(columns={'Name':'Full_Name'},inplace=True)

In [18]:
df["Age"] = df["Age"].apply(lambda x: x + 1)

In [19]:
print(df)

  Full_Name  Age  salary
0    Lokesh   23     200
1      Ravi   24     250
2       Anu   25     300
3      Ritu   26     350

In [10]:
df.iloc(0)

In [11]:
df.loc(0)

In [12]:
df[df['Age']>22]

   Name  Age
1  Ravi   23
2   Anu   24
3  Ritu   25

In [13]:
df["Salary"]=[20000,25000,45000,60000]

In [14]:
print(df)

     Name  Age  Salary
0  Lokesh   22   20000
1    Ravi   23   25000
2     Anu   24   45000
3    Ritu   25   60000

In [15]:
df.loc[0,'Age']=24

In [16]:
print(df)

     Name  Age  Salary
0  Lokesh   24   20000
1    Ravi   23   25000
2     Anu   24   45000
3    Ritu   25   60000

In [17]:
df.drop("Salary",axis=1,inplace=True)

In [18]:
print(df)

     Name  Age
0  Lokesh   24
1    Ravi   23
2     Anu   24
3    Ritu   25

In [19]:
df.sort_values(by='Age')

     Name  Age
1    Ravi   23
0  Lokesh   24
2     Anu   24
3    Ritu   25

In [20]:
df.isnull()

    Name    Age
0  False  False
1  False  False
2  False  False
3  False  False

In [21]:
df.dropna

<bound method DataFrame.dropna of      Name  Age
0  Lokesh   24
1    Ravi   23
2     Anu   24
3    Ritu   25>

In [22]:
df.fillna(0)

     Name  Age
0  Lokesh   24
1    Ravi   23
2     Anu   24
3    Ritu   25

In [23]:
df = pd.read_csv(r"C:\Users\lokes\OneDrive\Desktop\tech_layoffs_2026_tracker.csv")

In [24]:
print(df)

                     company layoff_date  jobs_cut  pct_workforce_cut  \
0                     Amazon  2026-01-15     16000                2.7
1                      Block  2026-02-28      4000               40.0
2          Meta Reality Labs  2026-01-20      1500               10.0
3                  Atlassian  2026-03-14      1600               10.0
4                     Oracle  2026-02-01     30000               15.0
5                 Salesforce  2026-01-10      1000                1.4
6                   Autodesk  2026-01-25      1000                9.0
7                       eBay  2026-01-28       800                5.0
8                  Pinterest  2026-02-10       675                4.0
9                   Ericsson  2026-01-15      1600               12.0
10                      ASML  2026-01-20      1700                3.4
11                 ams OSRAM  2026-02-05      2000               12.0
12                     Ocado  2026-01-30      1000                7.0
13           WiseTech Global  2026-02-20      2000               25.0
14                     Cisco  2026-02-15      6000                7.0
15                  T-Mobile  2026-02-02       363                0.1
16        SK Battery America  2026-03-16       958               37.3
17                 Walgreens  2026-03-11      1000                0.5
18                Telefonica  2026-01-15      5000                5.0
19                       xAI  2026-02-25        50                2.0
20        Palo Alto Networks  2026-02-18       500                2.0
21                  Livspace  2026-02-10      1000               15.0
22       General Motors Tech  2026-01-22      1000                2.0
23                   Workday  2026-01-28      2200                8.5
24            Ergo Insurance  2026-03-01       200                2.0
25              Algoma Steel  2026-03-07      1000               20.0
26  Meta Platforms (Planned)  2026-03-13     16000               20.0
27              Algoma Steel  2026-03-23      1000               20.0

                      sector      country          hq_city  ai_cited  \
0           E-Commerce/Cloud          USA          Seattle     False
1                    Fintech          USA    San Francisco      True
2            Social Media/VR          USA       Menlo Park      True
3        Enterprise Software    Australia           Sydney      True
4        Enterprise Software          USA           Austin      True
5                   CRM/SaaS          USA    San Francisco      True
6            Design Software          USA    San Francisco     False
7                 E-Commerce          USA         San Jose      True
8               Social Media          USA    San Francisco      True
9         Telecommunications       Sweden        Stockholm     False
10            Semiconductors  Netherlands        Veldhoven     False
11            Semiconductors      Austria     Premstaetten     False
12              Grocery Tech           UK         Hatfield      True
13        Logistics Software    Australia           Sydney      True
14  Networking/Cybersecurity          USA         San Jose     False
15        Telecommunications          USA         Bellevue     False
16              EV Batteries          USA      Commerce GA     False
17           Retail Pharmacy          USA     Deerfield IL     False
18        Telecommunications        Spain           Madrid     False
19               AI Research          USA    San Francisco      True
20             Cybersecurity          USA      Santa Clara     False
21      Interior Design Tech        India        Bangalore      True
22           Automotive Tech          USA          Detroit     False
23           Enterprise SaaS          USA    Pleasanton CA      True
24                 Insurance      Germany       Dusseldorf      True
25             Manufacturing       Canada  Sault Ste Marie     False
26           Social Media/AI          USA       Menlo Park      True
27             Manufacturing       Canada  Sault Ste Marie     False

                                    reason_stated  company_revenue_2025_bn  \
0        Reduce bureaucracy and management layers                    716.9
1   AI tools replace roles enabling smaller teams                     22.4
2             Pivot from metaverse to AI research                    164.5
3              Pivot to AI-first company strategy                      5.1
4               AI data centres replace human ops                     52.9
5          AI-driven efficiency and restructuring                     37.9
6            Post-Ansys acquisition restructuring                      5.9
7             AI-forward strategy in customer ops                     10.3
8       AI-forward content and marketing strategy                      3.6
9          Declining 5G demand and cost reduction                     24.3
10                           Chip market slowdown                     30.8
11         Cost restructuring and portfolio focus                      3.2
12          AI automation in warehouse operations                      3.8
13               AI replaces QA and testing teams                      3.2
14         Restructuring after Splunk acquisition                     56.9
15                      Restructuring sales teams                     80.0
16                              Slowing EV demand                      8.4
17          Store closures and cost restructuring                    140.0
18           Cost restructuring with compensation                     44.5
19                        Internal reorganization                      0.0
20              Post-CyberArk acquisition overlap                      8.0
21        AI design tools replace human designers                      0.3
22              Rethinking digital transformation                    180.0
23       AI investment and office space reduction                      8.5
24                   AI automates insurance tasks                      0.0
25                          Blast furnace closure                      2.8
26                 Offset AI infrastructure costs                    164.5
27                Blast furnace closure effective                      2.8

    ...  layoffs_2024  layoffs_2025                  verified_source  \
0   ...          4000         14000              CNBC / NetworkWorld
1   ...             0          1000                CNBC / Crunchbase
2   ...             0           500            InformationWeek / NYT
3   ...             0           500         TechRepublic / Metaintro
4   ...          6000         10000                          IBTimes
5   ...          1000          1000         NetworkWorld / Bloomberg
6   ...           500          1200                     NetworkWorld
7   ...          1000          1000                     NetworkWorld
8   ...          1500           200                     NetworkWorld
9   ...          3000          5000  InformationWeek / FierceNetwork
10  ...             0             0                     NetworkWorld
11  ...             0           500                     NetworkWorld
12  ...             0             0                     NetworkWorld
13  ...             0             0                      Medha Cloud
14  ...          4200          6000                    Computerworld
15  ...             0          5000                    FierceNetwork
16  ...             0             0                     Intellizence
17  ...          3000          2000                     Intellizence
18  ...             0          3000                    FierceNetwork
19  ...             0             0                       TechCrunch
20  ...             0           500                  InformationWeek
21  ...             0             0                      Medha Cloud
22  ...           500          1500                    Computerworld
23  ...          1750          1750                    Computerworld
24  ...             0             0                     Intellizence
25  ...             0             0                     Intellizence
26  ...             0             0         CNBC / Reuters / IBTimes
27  ...             0             0                     Intellizence

            month  quarter         region  layoff_size_category  \
0    January 2026  Q1 2026  North America            Mega (5K+)
1   February 2026  Q1 2026  North America         Large (2K-5K)
2    January 2026  Q1 2026  North America       Medium (500-2K)
3      March 2026  Q1 2026   Asia-Pacific       Medium (500-2K)
4   February 2026  Q1 2026  North America            Mega (5K+)
5    January 2026  Q1 2026  North America       Medium (500-2K)
6    January 2026  Q1 2026  North America       Medium (500-2K)
7    January 2026  Q1 2026  North America       Medium (500-2K)
8   February 2026  Q1 2026  North America       Medium (500-2K)
9    January 2026  Q1 2026         Europe       Medium (500-2K)
10   January 2026  Q1 2026         Europe       Medium (500-2K)
11  February 2026  Q1 2026         Europe       Medium (500-2K)
12   January 2026  Q1 2026         Europe       Medium (500-2K)
13  February 2026  Q1 2026   Asia-Pacific       Medium (500-2K)
14  February 2026  Q1 2026  North America            Mega (5K+)
15  February 2026  Q1 2026  North America          Small (<500)
16     March 2026  Q1 2026  North America       Medium (500-2K)
17     March 2026  Q1 2026  North America       Medium (500-2K)
18   January 2026  Q1 2026         Europe         Large (2K-5K)
19  February 2026  Q1 2026  North America          Small (<500)
20  February 2026  Q1 2026  North America          Small (<500)
21  February 2026  Q1 2026   Asia-Pacific       Medium (500-2K)
22   January 2026  Q1 2026  North America       Medium (500-2K)
23   January 2026  Q1 2026  North America         Large (2K-5K)
24     March 2026  Q1 2026         Europe          Small (<500)
25     March 2026  Q1 2026  North America       Medium (500-2K)
26     March 2026  Q1 2026  North America            Mega (5K+)
27     March 2026  Q1 2026  North America       Medium (500-2K)

    stock_reaction laid_off_vs_headcount_pct      data_as_of
0         Positive                      1.03  March 18, 2026
1         Positive                     40.00  March 18, 2026
2         Positive                      1.90  March 18, 2026
3         Positive                     10.00  March 18, 2026
4         Positive                     15.00  March 18, 2026
5         Positive                      1.39  March 18, 2026
6         Positive                      9.09  March 18, 2026
7         Positive                      7.27  March 18, 2026
8         Positive                     18.24  March 18, 2026
9         Positive                      1.52  March 18, 2026
10        Negative                      4.05  March 18, 2026
11        Positive                      9.52  March 18, 2026
12        Positive                      7.14  March 18, 2026
13        Positive                     25.00  March 18, 2026
14        Negative                      7.06  March 18, 2026
15        Negative                      0.51  March 18, 2026
16        Negative                     37.33  March 18, 2026
17        Negative                      0.32  March 18, 2026
18        Positive                      5.00  March 18, 2026
19         Neutral                      2.00  March 18, 2026
20        Positive                      3.33  March 18, 2026
21         Neutral                     14.29  March 18, 2026
22        Negative                      0.67  March 18, 2026
23        Positive                      8.53  March 18, 2026
24         Neutral                      2.22  March 18, 2026
25        Negative                     20.00  March 18, 2026
26        Positive                     20.25  March 18, 2026
27        Negative                     20.00  March 18, 2026

[28 rows x 26 columns]

In [25]:
df.head()

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,...,layoffs_2024,layoffs_2025,verified_source,month,quarter,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct,data_as_of
0,Amazon,2026-01-15,16000,2.7,E-Commerce/Cloud,USA,Seattle,False,Reduce bureaucracy and management layers,716.9,...,4000,14000,CNBC / NetworkWorld,January 2026,Q1 2026,North America,Mega (5K+),Positive,1.03,"March 18, 2026"
1,Block,2026-02-28,4000,40.0,Fintech,USA,San Francisco,True,AI tools replace roles enabling smaller teams,22.4,...,0,1000,CNBC / Crunchbase,February 2026,Q1 2026,North America,Large (2K-5K),Positive,40.00,"March 18, 2026"
2,Meta Reality Labs,2026-01-20,1500,10.0,Social Media/VR,USA,Menlo Park,True,Pivot from metaverse to AI research,164.5,...,0,500,InformationWeek / NYT,January 2026,Q1 2026,North America,Medium (500-2K),Positive,1.90,"March 18, 2026"
3,Atlassian,2026-03-14,1600,10.0,Enterprise Software,Australia,Sydney,True,Pivot to AI-first company strategy,5.1,...,0,500,TechRepublic / Metaintro,March 2026,Q1 2026,Asia-Pacific,Medium (500-2K),Positive,10.00,"March 18, 2026"
4,Oracle,2026-02-01,30000,15.0,Enterprise Software,USA,Austin,True,AI data centres replace human ops,52.9,...,6000,10000,IBTimes,February 2026,Q1 2026,North America,Mega (5K+),Positive,15.00,"March 18, 2026"

In [26]:
df.tail()

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,...,layoffs_2024,layoffs_2025,verified_source,month,quarter,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct,data_as_of
23,Workday,2026-01-28,2200,8.5,Enterprise SaaS,USA,Pleasanton CA,True,AI investment and office space reduction,8.5,...,1750,1750,Computerworld,January 2026,Q1 2026,North America,Large (2K-5K),Positive,8.53,"March 18, 2026"
24,Ergo Insurance,2026-03-01,200,2.0,Insurance,Germany,Dusseldorf,True,AI automates insurance tasks,0.0,...,0,0,Intellizence,March 2026,Q1 2026,Europe,Small (<500),Neutral,2.22,"March 18, 2026"
25,Algoma Steel,2026-03-07,1000,20.0,Manufacturing,Canada,Sault Ste Marie,False,Blast furnace closure,2.8,...,0,0,Intellizence,March 2026,Q1 2026,North America,Medium (500-2K),Negative,20.00,"March 18, 2026"
26,Meta Platforms (Planned),2026-03-13,16000,20.0,Social Media/AI,USA,Menlo Park,True,Offset AI infrastructure costs,164.5,...,0,0,CNBC / Reuters / IBTimes,March 2026,Q1 2026,North America,Mega (5K+),Positive,20.25,"March 18, 2026"
27,Algoma Steel,2026-03-23,1000,20.0,Manufacturing,Canada,Sault Ste Marie,False,Blast furnace closure effective,2.8,...,0,0,Intellizence,March 2026,Q1 2026,North America,Medium (500-2K),Negative,20.00,"March 18, 2026"

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   company                        28 non-null     object
 1   layoff_date                    28 non-null     object
 2   jobs_cut                       28 non-null     int64
 3   pct_workforce_cut              28 non-null     float64
 4   sector                         28 non-null     object
 5   country                        28 non-null     object
 6   hq_city                        28 non-null     object
 7   ai_cited                       28 non-null     bool
 8   reason_stated                  28 non-null     object
 9   company_revenue_2025_bn        28 non-null     float64
 10  pre_layoff_headcount           28 non-null     int64
 11  stock_change_day_pct           28 non-null     float64
 12  simultaneous_ai_investment_bn  28 non-null     float64
 13  roles_most_affected            28 non-null     object
 14  replacement_roles              28 non-null     object
 15  ceo_quote                      28 non-null     object
 16  layoffs_2024                   28 non-null     int64
 17  layoffs_2025                   28 non-null     int64
 18  verified_source                28 non-null     object
 19  month                          28 non-null     object
 20  quarter                        28 non-null     object
 21  region                         28 non-null     object
 22  layoff_size_category           28 non-null     object
 23  stock_reaction                 28 non-null     object
 24  laid_off_vs_headcount_pct      28 non-null     float64
 25  data_as_of                     28 non-null     object
dtypes: bool(1), float64(5), int64(4), object(16)
memory usage: 5.6+ KB

In [28]:
df.describe()

,jobs_cut,pct_workforce_cut,company_revenue_2025_bn,pre_layoff_headcount,stock_change_day_pct,simultaneous_ai_investment_bn,layoffs_2024,layoffs_2025,laid_off_vs_headcount_pct
count,28.000000,28.000000,28.00000,2.800000e+01,28.000000,28.000000,28.000000,28.000000,28.000000
mean,3612.357143,10.639286,63.62500,1.076631e+05,0.832143,14.046429,944.642857,1951.785714,10.452143
std,6546.591373,10.433505,139.44986,2.915339e+05,1.742721,34.751824,1615.511574,3328.482085,10.719330
min,50.000000,0.100000,0.00000,2.500000e+03,-2.100000,0.000000,0.000000,0.000000,0.320000
25%,989.500000,2.525000,3.50000,8.750000e+03,-0.325000,0.000000,0.000000,0.000000,1.975000
50%,1000.000000,7.750000,9.40000,1.850000e+04,0.650000,0.450000,0.000000,500.000000,7.205000
75%,2050.000000,15.000000,53.90000,8.050000e+04,1.850000,2.250000,1125.000000,1812.500000,15.810000
max,30000.000000,40.000000,716.90000,1.550000e+06,5.800000,115.000000,6000.000000,14000.000000,40.000000

In [29]:
df.shape

(28, 26)

In [30]:
df.columns

Index(['company', 'layoff_date', 'jobs_cut', 'pct_workforce_cut', 'sector',
       'country', 'hq_city', 'ai_cited', 'reason_stated',
       'company_revenue_2025_bn', 'pre_layoff_headcount',
       'stock_change_day_pct', 'simultaneous_ai_investment_bn',
       'roles_most_affected', 'replacement_roles', 'ceo_quote', 'layoffs_2024',
       'layoffs_2025', 'verified_source', 'month', 'quarter', 'region',
       'layoff_size_category', 'stock_reaction', 'laid_off_vs_headcount_pct',
       'data_as_of'],
      dtype='object')

In [31]:
df.dtypes

company                           object
layoff_date                       object
jobs_cut                           int64
pct_workforce_cut                float64
sector                            object
country                           object
hq_city                           object
ai_cited                            bool
reason_stated                     object
company_revenue_2025_bn          float64
pre_layoff_headcount               int64
stock_change_day_pct             float64
simultaneous_ai_investment_bn    float64
roles_most_affected               object
replacement_roles                 object
ceo_quote                         object
layoffs_2024                       int64
layoffs_2025                       int64
verified_source                   object
month                             object
quarter                           object
region                            object
layoff_size_category              object
stock_reaction                    object
laid_off_vs_headcount_pct        float64
data_as_of                        object
dtype: object

In [32]:
df.memory_usage()

Index                            132
company                          224
layoff_date                      224
jobs_cut                         224
pct_workforce_cut                224
sector                           224
country                          224
hq_city                          224
ai_cited                          28
reason_stated                    224
company_revenue_2025_bn          224
pre_layoff_headcount             224
stock_change_day_pct             224
simultaneous_ai_investment_bn    224
roles_most_affected              224
replacement_roles                224
ceo_quote                        224
layoffs_2024                     224
layoffs_2025                     224
verified_source                  224
month                            224
quarter                          224
region                           224
layoff_size_category             224
stock_reaction                   224
laid_off_vs_headcount_pct        224
data_as_of                       224
dtype: int64

In [33]:
df.isnull().sum()

company                          0
layoff_date                      0
jobs_cut                         0
pct_workforce_cut                0
sector                           0
country                          0
hq_city                          0
ai_cited                         0
reason_stated                    0
company_revenue_2025_bn          0
pre_layoff_headcount             0
stock_change_day_pct             0
simultaneous_ai_investment_bn    0
roles_most_affected              0
replacement_roles                0
ceo_quote                        0
layoffs_2024                     0
layoffs_2025                     0
verified_source                  0
month                            0
quarter                          0
region                           0
layoff_size_category             0
stock_reaction                   0
laid_off_vs_headcount_pct        0
data_as_of                       0
dtype: int64

In [34]:
df.sample()

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,...,layoffs_2024,layoffs_2025,verified_source,month,quarter,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct,data_as_of
18,Telefonica,2026-01-15,5000,5.0,Telecommunications,Spain,Madrid,False,Cost restructuring with compensation,44.5,...,0,3000,FierceNetwork,January 2026,Q1 2026,Europe,Large (2K-5K),Positive,5.0,"March 18, 2026"

In [35]:
df['jobs_cut'].sum()

101146

In [36]:
df['ai_cited'].value_counts()

ai_cited
False    14
True     14
Name: count, dtype: int64

In [37]:
df.groupby('sector')['jobs_cut'].mean()

sector
AI Research                    50.0
Automotive Tech              1000.0
CRM/SaaS                     1000.0
Cybersecurity                 500.0
Design Software              1000.0
E-Commerce                    800.0
E-Commerce/Cloud            16000.0
EV Batteries                  958.0
Enterprise SaaS              2200.0
Enterprise Software         15800.0
Fintech                      4000.0
Grocery Tech                 1000.0
Insurance                     200.0
Interior Design Tech         1000.0
Logistics Software           2000.0
Manufacturing                1000.0
Networking/Cybersecurity     6000.0
Retail Pharmacy              1000.0
Semiconductors               1850.0
Social Media                  675.0
Social Media/AI             16000.0
Social Media/VR              1500.0
Telecommunications           2321.0
Name: jobs_cut, dtype: float64

In [38]:
df.groupby('country')['jobs_cut'].sum().sort_values(ascending=False)

country
USA            83046
Spain           5000
Australia       3600
Austria         2000
Canada          2000
Netherlands     1700
Sweden          1600
India           1000
UK              1000
Germany          200
Name: jobs_cut, dtype: int64

In [39]:
df.groupby('stock_reaction')['jobs_cut'].mean()

stock_reaction
Negative    1627.625000
Neutral      416.666667
Positive    5110.294118
Name: jobs_cut, dtype: float64

In [40]:
df.groupby("ai_cited")["stock_change_day_pct"].mean()

ai_cited
False   -0.242857
True     1.907143
Name: stock_change_day_pct, dtype: float64

In [41]:
df.sort_values(by="jobs_cut",ascending=False).head(5)

,company,layoff_date,jobs_cut,pct_workforce_cut,sector,country,hq_city,ai_cited,reason_stated,company_revenue_2025_bn,...,layoffs_2024,layoffs_2025,verified_source,month,quarter,region,layoff_size_category,stock_reaction,laid_off_vs_headcount_pct,data_as_of
4,Oracle,2026-02-01,30000,15.0,Enterprise Software,USA,Austin,True,AI data centres replace human ops,52.9,...,6000,10000,IBTimes,February 2026,Q1 2026,North America,Mega (5K+),Positive,15.00,"March 18, 2026"
0,Amazon,2026-01-15,16000,2.7,E-Commerce/Cloud,USA,Seattle,False,Reduce bureaucracy and management layers,716.9,...,4000,14000,CNBC / NetworkWorld,January 2026,Q1 2026,North America,Mega (5K+),Positive,1.03,"March 18, 2026"
26,Meta Platforms (Planned),2026-03-13,16000,20.0,Social Media/AI,USA,Menlo Park,True,Offset AI infrastructure costs,164.5,...,0,0,CNBC / Reuters / IBTimes,March 2026,Q1 2026,North America,Mega (5K+),Positive,20.25,"March 18, 2026"
14,Cisco,2026-02-15,6000,7.0,Networking/Cybersecurity,USA,San Jose,False,Restructuring after Splunk acquisition,56.9,...,4200,6000,Computerworld,February 2026,Q1 2026,North America,Mega (5K+),Negative,7.06,"March 18, 2026"
18,Telefonica,2026-01-15,5000,5.0,Telecommunications,Spain,Madrid,False,Cost restructuring with compensation,44.5,...,0,3000,FierceNetwork,January 2026,Q1 2026,Europe,Large (2K-5K),Positive,5.00,"March 18, 2026"

In [60]:
df[["company_revenue_2025_bn", "jobs_cut"]].corr()

                         company_revenue_2025_bn  jobs_cut
company_revenue_2025_bn                 1.000000  0.434519
jobs_cut                                0.434519  1.000000